### ISSUE TITLE
Nice but doesn't size!

### ISSUE THREAD

**Issue by everlof** [stokatyan/ScrollCounter#10]
Thanks for a nice component. Unfortunately I doesn't work well when I try to use it right-aligned, due the sizing being incorrect. When adding/removing digits, the size of the whole view isn't updated, at least if the view is positioned using auto-layout.

**Comment by stokatyan** [comment]
Hi @everlof -- sorry for the late reply I just saw this!

You should be able to use auto layout and right alignment if you use layout anchors instead of the conventional auto layout spacing.  Good luck!

**Comment by everlof** [comment]
No problem - I did try that didn't work, I went with https://github.com/thomasrzhao/TRZNumberScrollView instead! Have a good day!

**Comment by stokatyan** [comment]
Nice, and thanks for bringing this issue up.  I'll look into auto layout as soon as I can.
