### ISSUE TITLE
Support for grouping the digits by arbitrary number

### ISSUE THREAD

**Issue by ngeri** [stokatyan/ScrollCounter#12]
It would be nice to have a new init parameter where one could specify how many digits should be grouped together.

**Comment by stokatyan** [comment]
As of now I have no plans to update the project unless there is some iOS update that breaks the project. In the meantime, I'm happy to review a PR if you want to give it a shot :)

Also, you might be able to get what you are looking for by using the `public DigitScrollCounter` to group digits the way you'd like to.
