### ISSUE TITLE
Initializing the digitScrollers

### ISSUE THREAD

**Issue by RobertLOwens** [stokatyan/ScrollCounter#8]
Greetings! 

Attempting to use your cocoa pod. Getting an issue when initializing the NumberScrollCounter. In the public init, you have the line: 

`frame.size.height = digitScrollers.first!.height`

However, the digitScrollers are set as the top as an empty array and never set to a value. So – I am getting an "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value" error when attempting to use this. Any suggestions? 

Here is my call trying to use the NumberScrollCounter: 

`let label = NumberScrollCounter(value: 0, scrollDuration: 0.33, decimalPlaces: 0, font: UIFont(name: "TitanOne", size: 56)!, textColor: K.Colors.yellow!, animateInitialValue: true, gradientColor: .black, gradientStop: 0.2)`

**Comment by RobertLOwens** [comment]
So, I figured out the issue here, the NumberScrollCounter can't handle a number with 0 decimal places. Please make this a future enhancement!

**Comment by stokatyan** [comment]
Hi @RobertLOwens I apologize for the late response, I just saw this issue!

Thanks for pointing out the problem and sharing your workaround.  I will try to reproduce and fix this over the weekend.

**Comment by stokatyan** [comment]
This issue is fixed in version 0.0.2 (run `pod update ScrollCounter` to get the latest version).

The fix can be viewed in this commit: https://github.com/stokatyan/ScrollCounter/commit/6e9e9dd5c1bf01012ba15f7aaeb556624786cb87

Thanks for reporting the issue @RobertLOwens!
